### PR TITLE
tenc-redistribute

### PR DESCRIPTION
**Pull request by ArrowM**
**What**
TENC training is broken into segments relative to model save frequency.

**Example**
Switch TENC periods from the top illustration to the bottom illustration.
image
Without this commit, if I train for 100 epochs w/ a save freq of 20, the output models with have different TENC %. With this change, they should all have the same %.

**Concerns**
I prefer this to the default behavior, but one potential issue is that the TENC ratio gets rounded, which might be significant w/ small save frequencies. For example, with the input of `save freq = 5, TENC = 0.5`, the effective TENC is `0.6`.

### CODE REVIEW

**Comment by d8ahazard** [comment]
Assuming you've trained this way, and starting and stopping tenc doesn't break anything?

**Comment by ArrowM** [comment]
I trained 1 model with this and it seemed to work as expected.

**Comment by d8ahazard** [comment]
Okay, so, I fixed the conflict as a result of adding the bit to optionally train the unet...but, we should probably have something in the UI that checks if unet is disabled and sets the train tenc percentage to 100, else people will get confused.

**Comment by Zuxier** [comment]
After seeing good effects from long warmups; Tenc training splitted like that will deny the benefits of warmup(tenc wise).
I would like it to be optional.

**Comment by d8ahazard** [comment]
Closing, as I've cherry-picked this into latest ligherlora.

**Pull request closed without merging**
