### PR TITLE
Fix text encoder training

### PR DESCRIPTION
**Pull request by echo1001**
Just a quick bug fix. The text encoder wasn't training on the latest updates and this looks to be the cause.

### CODE REVIEW

**Comment by d8ahazard** [comment]
Hell's Bells. That was the issue? LOL. Does this then fix #365 and #349 without me having to remove the whole "stop training text encoder after" segment of stuff?

**Comment by echo1001** [comment]
I don't think it fixes them entirely, that config issue seems to be unrelated. But I was also racking my brain to figure out why my training hadn't been working correctly, I had to load it up in a debugger to find it. haha.

I should also note that the stopping the text encoder training doesn't seem to be working correctly. I haven't looked in to why yet though. But I don't think it's worth reverting your commit over.

`Traceback (most recent call last):
  File "/home/echo1001/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 1021, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/accelerate/utils/operations.py", line 491, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 313, in forward
    sample, res_samples = downsample_block(
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 623, in forward
    hidden_states = torch.utils.checkpoint.checkpoint(
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/unet_2d_blocks.py", line 616, in custom_forward
    return module(*inputs, return_dict=return_dict)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 203, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/diffusers/models/attention.py", line 451, in forward
    hidden_states = self.attn2(norm_hidden_states, context=context) + hidden_states
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 24, in forward_default
    key = self.to_k(context)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/echo1001/stable-diffusion-webui/venv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x77 and 768x320)
`

**Comment by mrgreaper** [comment]
Atleast now I know why one of the sameple images of me came out as a house... thought the AI was just calling me fat.

**Comment by d8ahazard** [comment]
I wonder if it was bumping the diffusers version? We really need 0.9.0 for
v2 support.

**Comment by echo1001** [comment]
I somewhat doubt it. I'm starting to think it's due to this line. 

https://github.com/d8ahazard/sd_dreambooth_extension/blob/3e4f9cb0087adec3700fb3a0ae25429c6a5d536c/dreambooth/train_dreambooth.py#L1016

What's probably happening is that the None value passed in to it is skipping the text encoding, so it's trying to send the tokens directly through the rest of the pipeline.

**Comment by echo1001** [comment]
It is a problem, however, I had latent caching enabled. So it was using the latents from the batch.

I added a quick change to leave the encoder alone, but freeze the weights.

**Comment by seoeaa** [comment]
I understand that training does not work now? trained three times and the result is 0 , the text does not affect

**Comment by d8ahazard** [comment]
Have you updated to the latest version? It's working over here...

**Comment by seoeaa** [comment]
> Вы обновились до последней версии? Здесь работает...
updated now I can not create a model

**Comment by seoeaa** [comment]
> Вы обновились до последней версии? Здесь работает...

Traceback (most recent call last):
  File "/home/aleks/SD/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/home/aleks/SD/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/home/aleks/SD/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 1006, in extract_checkpoint
    src, has_ema, status
UnboundLocalError: local variable 'has_ema' referenced before assignment

Traceback (most recent call last):
  File "/home/aleks/anaconda3/lib/python3.9/site-packages/gradio/routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "/home/aleks/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/aleks/anaconda3/lib/python3.9/site-packages/gradio/blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:

**Comment by seoeaa** [comment]
> Вы обновились до последней версии? Здесь работает...
i tried with huggingface. and local worked

**Comment by Humanoidme** [comment]
Does this fix the training? Can SD 2.0 still be used after this fix?

**Pull request closed without merging**
