### PR TITLE
feat: add read label from filename or txt file.

### PR DESCRIPTION
**Pull request by CrazyBoyM**
This makes it possible to train the style of the model by using different labels for each image.

### CODE REVIEW

**Comment by d8ahazard** [comment]
Thanks!

**Comment by CrazyBoyM** [comment]
> Does "ignoring non-image file..." mean that it is not picking up the txt files' content labels? Or is it ignoring the txt files for some other process?

sorry for my English, do you mean add a "ignoring non-image file" option in the page? I see there already a 'is_image' function in the train code to filter non-image files in the image datasets folder.And it will just read the txt file's content as the image's label for train.

**Comment by CrazyBoyM** [comment]
for example to use the "use_filename_as_label" option:
```
1girl,blue eyes,brown hair... .jpg
1girl,blue eyes,brown hair,... .jpg
...
as labels.jpg or labels.png
```
or with the "use_txt_as_label" option, it should be:
```
dataset folder files:
0001.jpg
0001.txt
0002.jpg
0002.txt
...

0001.txt content (labels):
1girl,blue eyes,brown hair...
```

**Comment by Jonseed** [comment]
I mean there is now an option to use <filename>.txt as the image labels instead of the instance prompt. Running training shows "ignoring non-image file..." on all the txt files in the terminal. So is it not using those txt files, or is it? Maybe it is ignoring the txt files for some other process?

**Comment by CrazyBoyM** [comment]
> 

the non-image file will be auto ignored when read images.And txt file's content will be read as label.

**Pull request merged**
