### PR TITLE
Using webui command line args to set mount path 

### PR DESCRIPTION
**Pull request by nekoyama32767**
https://github.com/d8ahazard/sd_dreambooth_extension/issues/42

### CODE REVIEW

**Comment by d8ahazard** [comment]
Very nice. Only thing missing is a launch.py file in the root of the project with a method called "preload" that accepts the parser as an input.

preload(parser)

See here for the new commit that makes this possible:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4488/files

**Comment by nekoyama32767** [comment]
Latest webui has merged preload.
I try it works on webui commit `98947d173e3f1667eba29c904f681047dea9de90`
To avoid old webui version  (which does not support --dreambooth-models-path) errors, it use try-except block
```
try:
    cmd_dreambooth_models_path = shared.cmd_opts.dreambooth_models_path
except:
    cmd_dreambooth_models_path = None

```

**Comment by nekoyama32767** [comment]
Actually defining `cmd_dreambooth_models_path ` in a individual module as utility and import it in other scripts is more expect.
Shall i do that?

**Comment by d8ahazard** [comment]
> cmd_dreambooth_models_path

We've already got support for "adding" command-line options without having to create any custom code.

We just need a 

> Actually defining `cmd_dreambooth_models_path ` in a individual module as utility and import it in other scripts is more expected. Shall I do that?

I was mistaken, looks like I pre-staged the "preload.py" script already, so it should just work.

image

**Pull request merged**
