### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by tsngo**
https://github.com/d8ahazard/sd_dreambooth_extension/issues/817 and https://github.com/d8ahazard/sd_dreambooth_extension/issues/823

### CODE REVIEW

**Comment by d8ahazard** [comment]
So, the fix for concepts list I understand.

The caching changes may break something. The point is, if the vae or tokenizer exists, then cache something. If not, then at least put an entry in the cache, else we'll get a keynotfound error later. This will definitely cause issues if using "debug buckets".

**Comment by tsngo** [comment]
I tried `debug buckets` and it's working fine. What's the exact case that should cache None? Right now in main, it caches None even when image_path was already cached.

**Comment by d8ahazard** [comment]
It's just a placeholder, so it should cache None only when adding a new entry and caching of latents is disabled. Theoretically, this would never actually overwrite a valid entry, but it'd be better to only cache None when adding a new entry.

**Comment by tsngo** [comment]
My use case is I use a single set of class images for multiple concepts. I think that's why I have the same image_path come up multiple time for classification images. Anyways, let me see if I can modify so it also defaults to None if not yet cached

**Comment by tsngo** [comment]
So far anything I tried causes error when encountering None. Only thing that works is what I have in the PR currently

**Comment by mykeehu** [comment]
Need fix in dev in db_dataset.py:
image

**Comment by tsngo** [comment]
Created a PR for dev

**Comment by d8ahazard** [comment]
So, I merged your other PR to dev - does this need to remain open? I don't think so, so I'm closing it. If I'm mistaken, let me know. ;)

**Pull request closed without merging**
