### PR TITLE
Webhook integration

### PR DESCRIPTION
**Pull request by Janca**
Accidentally pushed to my main instead of the feature branch 🙄, but regardless, I have merged the changes from our branches and it should be ready for a pull whenever.

### CODE REVIEW

**Comment by d8ahazard** [comment]
Hey there again!

Everything here looks great - but I merged the BetterBuckets branch in today, and didn't want to make you have to fix everything again.

So, I reworked your change a bit, and commited via 75ff376. Hope you don't mind.

Here's what I changed:

Added the webhook URL to the "Miscellaneous" section under settings, right under the API key. 

Made the "Test" button into "Save and Test Webhook". This way, we aren't trying to store the webhook URL to a specific model, but instead, keeping the URL stored globally. 

Updated the call that actually sends the webhook so that it's always called when samples are saved - but only actually does anything if the webhook is valid and recognized.

Updated the "send the things" call to accept a list of images and prompts. If a list of images is passed, then it will automagically create a grid of the images and return them to the user. If it's a single image, it will pass as usual. 

Updated the usage of the "send the things" call in train_dreambooth so that it fires after all samples are generated, versus sending each individual sample. 

If this isn't the behavior you want, please let me know, and I can redo it so that it sends individual calls to the hook for each image in the list, or something like that.

Oh, and the output of testing the webhook will now go to db_status. ;)

Thanks for the contribution!!

**Comment by Janca** [comment]
This is great, the first time I created the Discord feature, I noticed someone forked it for Telegram as well, which also requires another secret key, so I put created the tab because I planned on expanded the feature settings for other webhook integrations and Telegram will require another input box. Plus I was going to add options to send in grid or not, but just combining them by default is fine too. And discord lets your customize embeds so I was going to add options to do that as well. Overall, if needed, it can be moved back into its own tab. I'm just happy its merged so I don't need to maintain a separate branch

**Comment by artemisiaaaa** [comment]
I should be getting samples via the discord webhook, right? if yes it's not working for me. I do get "This is a test message from the A1111 Dreambooth Extension." in the channel when I click "Save and Test Webhook" tho, but no samples when I train

**Comment by Janca** [comment]
#913

**Pull request closed without merging**
