### PR TITLE
Update api.py

### PR DESCRIPTION
**Pull request by TheFlyingPirate**
Added few more endpoints to make running the api more suitable for environments such as runpod.io

### CODE REVIEW

**Comment by d8ahazard** [comment]
Nice!

One thought - in your upload scripts, we're just hardcoding it to "/training"?

How will that affect windoze users like myself? 

IMHO, we should be using the "model_dir" parameter a la the UI, which then looks at whether the --dreambooth_models_dir param was passed to command line args. If we have the command line args, then it should be shared.cmd_opts.dreambooth_models_dir/model_dir/training, else shared.models_dir/dreambooth/model_dir/training

**Comment by TheFlyingPirate** [comment]
I tested it under windows and it didn't cause any issues, I just hardcoded it as /training to ensure that one can't upload a file that overwrites a main file from the webui and causes issues, alternatively we can use a different folder

**Comment by TheFlyingPirate** [comment]
I implemented the change let me just test it here quick to see if it works

**Comment by d8ahazard** [comment]
I can merge this, but you'll probably want to update it again to make it work with the revamp I did on params.

Sorry. I'll try to avoid changing things too much in the future.

**Comment by TheFlyingPirate** [comment]
Don't worry about it, I get right to it

**Pull request closed without merging**
