### PR TITLE
Integrating the "Shuffle After Epoch" code by InB4DevOps

### PR DESCRIPTION
**Pull request by MatthewK78**
Howdy! This is an attempt to integrate code by @InB4DevOps that shuffles class images to potentially improve training quality. I'm very new to Python and GitHub so I apologize in advance if I make any rookie mistakes.

Here's a Reddit post showing what it does:  [https://www.reddit.com/r/DreamBooth/comments/yj51zx/improved_dreambooth_training_heres_the_source/](https://www.reddit.com/r/DreamBooth/comments/yj51zx/improved_dreambooth_training_heres_the_source/)

Here's where I found the code:  [https://github.com/InB4DevOps/diffusers/tree/main/examples/dreambooth](https://github.com/InB4DevOps/diffusers/tree/main/examples/dreambooth)

Please test and let me know if there are any issues, I'll do my best to figure out how to fix them. Thanks!

### CODE REVIEW

**Comment by InB4DevOps** [comment]
I will soon have a PR ready for this to be included in @ShivamShrirao 's diffusers fork. 
While I appreciate your work I think it'll be easier for @d8ahazard to rebase his changes onto @ShivamShrirao repo instead of pulling these changes.

In the end it's up to @d8ahazard :)

**Comment by d8ahazard** [comment]
> I will soon have a PR ready for this to be included in @ShivamShrirao 's diffusers fork. While I appreciate your work I think it'll be easier for @d8ahazard to rebase his changes onto @ShivamShrirao repo instead of pulling these changes.
> 
> In the end it's up to @d8ahazard :)

Honestly, with all the extra stuff we've been schlepping into this lately, I've been seriously considering asking @ShivamShrirao if he just wants to start working together on this, as I imagine a lot of the changes we're making can benefit the upstream project and general community as well. Plus, it's less for me to maintain.

As such, I'm not really opposed to adding it here, and then maybe just submitting one "Mother of all Pull Requests" to add the changes to his repo.

**Comment by MatthewK78** [comment]
This might be a nice preview for people in the meantime, especially for impatient people like myself. There's one thing I'd like to fix first. It requires having Train Text Encoder enabled and Don't Cache Latents disabled, so I've been looking into a way to automagically enable/disable those if the user clicks on Shuffle After Epoch. I guess the other way would be to just throw an error message.

**Comment by d8ahazard** [comment]
That's really easy to do. If you take a look at the main.pi script, there
are several other examples of changing other variables when a checkbox is
clicked.

**Comment by MatthewK78** [comment]
Awesome, thanks! I figured it would be, I just haven't had enough time to dive into that issue yet. I'll try to get that done today.

**Comment by d8ahazard** [comment]
Something like this:

``
db_shuffle_after_epoch.change(
            fn=lambda x: {
                db_not_cache_latents: False if x else db_not_cache_latents,
                db_train_text_encoder: True if x else db_train_text_encoder
            },
            inputs=[db_shuffle_after_epoch,
                    db_not_cache_latents,
                    db_train_text_encoder
                    ],
            outputs=[db_not_cache_latents, db_train_text_encoder]
        )

`

At least, I *think* it should work, assuming that's what you call the checkbox. I haven't tried passing the input directly back to the output like this, but it didn't error in my IDE, so I imagine it should do what's expected.

Only downside is that there's not a simple way of tracking the original state of the buttons if this is unchecked, but that's not a huge issue in my mind.

**Comment by MatthewK78** [comment]
Thanks! I was close but had a few things off (still learning Python and Gradio). Only had to slightly modify your example, otherwise I was getting a recursion error.

**Comment by ShivamShrirao** [comment]
Hi @d8ahazard . I'm open if u want to make pull requests to my repo. I myself haven't been able to give that much time to it lately so would be great to have help.

**Comment by d8ahazard** [comment]
> Hi @d8ahazard . I'm open if u want to make pull requests to my repo. I myself haven't been able to give that much time to it lately so would be great to have help.

Awesome!

Aside from this feature, we've also added configurable length for the text encoder padding, reading prompts from training images, and more config params for class images, including prompts and negative prompts for the concepts list.

Would you prefer I submit individual PRs for each feature/addition, or is one big one acceptable?

**Comment by ShivamShrirao** [comment]
If it's easier for you one big will be fine. Just hoping you have done good amount of testing as I won't be able to test everything.

Btw in your README fp16 mixed precision reduces memory usage but not at cost of speed. It actually increases speed on modern GPUs with tensor cores, so anything after the RTX launch.

**Review by d8ahazard — COMMENTED** [review]
IMHO, it's probably better to disable shuffle_after_epoch if one of these is changed, versus locking the button, which I'd find more confusing, unless they were outright disabled/greyed out.

**Comment by MatthewK78** [comment]
Yep I agree, that does make more sense. Done.  :)

**Comment by d8ahazard** [comment]
@InB4DevOps @MatthewK78 - So this only shuffles the dataset after the first epoch, meaning we need to run with a combination of steps/epochs for this to have any effect?

So, like, if I train a model for 2k steps, train it for another 2k, etc, this won't do anything?

If so, can we make it just shuffle the dataset every time, regardless of epoch?

**Comment by MatthewK78** [comment]
Yes, I tested it with multiple epochs, but I also noticed it doesn't do it when it's only saving a ckpt after the specified steps interval. It will probably have to re-cache latents at each save interval similar to how it does with epochs. I'll see if I can figure out the code to make it happen, although since it's @InB4DevOps code he would undoubtedly be better at it, but I completely understand if he's too busy and needs to devote time and energy to something else. I'll see what I can do.  :)

**Comment by InB4DevOps** [comment]
The main idea behind my change is that the dataset is recreated (and reshuffled and recached) before every epoch starting with the second epoch, so yeah, you need to make sure that this recreation happens every epoch. 
If you need help, let me know :)

**Comment by d8ahazard** [comment]
> The main idea behind my change is that the dataset is recreated (and reshuffled and recached) before every epoch starting with the second epoch, so yeah, you need to make sure that this recreation happens every epoch. If you need help, let me know :)

I think maybe the implementation by @MatthewK78 missed this part. Looking at the current code, I see the shuffle seems to be done by the cache_latents function, which seems to run once during main setup, and again after the first epoch? So, if that's the case, then I think we're all set with this one, no?

**Comment by InB4DevOps** [comment]
I'll look into it later..

**Comment by MatthewK78** [comment]
Sorry for the delayed response. I tried to match up the code as best as I could, but it's entirely possible I missed something; as I've said before I am new to Python/Torch/Gradio/GitHub and stumbled my way through this. I did verify it is calling _get_random_class_image_index at each epoch. I haven't had time to work on this more, I'll try to get to it soon.

**Comment by d8ahazard** [comment]
Closing, as I've incorporated this into #288 

Thank you both for the contribution.

**Comment by MatthewK78** [comment]
Sorry, life happened and I wasn't able to dedicate any time to it the past several days. Thanks for reworking it and integrating it! 😊👍

**Comment by InB4DevOps** [comment]
@d8ahazard you might also want to update the readme.md :)

**Pull request closed without merging**
