### PR TITLE
[dev] Add configurable model conversion for training

### PR DESCRIPTION
**Pull request by ExponentialML**
Due to the multitude of configuration files flying around, this adds options for user to tune the model in two, specific meaningful ways. 

I've chosen to create a bunch of different configs (which seems to be common) rather than through code. This will prevent key value pairs from being added to any new models added in the future.

Untested (this is why WIP), but I consider this PR to be one that will not scrapped once tested.

- **"Train Conditioning Stage":** "Trains the conditioning stage of the model. Leads to better editability.",

- **"Unfreeze Model":** "Unfreezes the model for training. Uses more VRAM, but allows for better training and editability."

- **All**: `[Python code: Returns a config with the two above parameters.]`

For those that know how, feel free to pull this PR and test it out.

**TODO**

- [  X  ] Copy YAML config without `unfreeze_model` after converting diff to sd. As of now you can just manually edit the key out after generating a ckpt. 

-  [ X ] Create option to train unfrozen model when creating a new model.

-  [ X ] Train everything *but* normalization layers when training the text encoder on an unfrozen model. This one could be an incredible addition as it has quite an impact on model performance.

-  [ X ] Redo Yaml config files. 

-  [ X ] Update Yaml config functions and conditions to match changes.

-  [ X ] Make conditioning stage the default. There's no reason to *not* have it on.

### CODE REVIEW

**Comment by ExponentialML** [comment]
Discovering ***a lot*** while doing this PR. It will be a little bit more than initially planned.
Updated todos if you want to stay up to date.

**Comment by ExponentialML** [comment]
image
Screenshot_2023-01-22_13-45-38
Screenshot_2023-01-22_13-47-35


Here are the features from this branch.

:ice_cube:  **"Freeze CLIP Normalization Layers":** "Keep the normalization layers of CLIP frozen during training. Advanced usage, may increase model performance and editability."

:sun_with_face:  **"Unfreeze Model":**  "Unfreezes model layers and allows for potentially better training, but makes increased VRAM usage more likely."

```
LoRA Rank:  100
UNET LR: 1e-4
Text Encoder LR: 1e-7 
Weight Decay: 1e-4

No class or regularization images
Instance Prompt: a ulf character 

SD v1-5
Batch size and gradient accumulation = 2. 500 epochs.
```

Examples randomly grabbed from Google images with little thought, non cherry picked.
As always, please test before merge :pray: .

**Review by d8ahazard — APPROVED** [review]

**Comment by d8ahazard** [comment]
That's what we have the /dev branch for, so I can merge and test. ;)

**Comment by FurkanGozukara** [comment]
@ExponentialML could you give some more information regarding Unfreeze Model

currently we are training unet and clip and the vector tokens
what else there is to training? so what is Unfreeze Model doing? 


Freeze CLIP Normalization Layers when this is set true

so the clip is frozen but only token vectors are trained? am i correct? this is like textual inversion in this manner right? 

thank you so much for answers

**Pull request merged**
