### PR TITLE
rm tensorflow, use tensorboard for log parsing

### PR DESCRIPTION
**Pull request by zehongs**
## Describe your changes
In the main branch, tensorflow is only intended for log parsing. But it also brings many annoying messages in the terminal. And may cause memory leaks after training.
I found tensorboard **itself** could achieve logging and log parsing. 
See: 
1. https://www.legendu.net/en/blog/read-tensorboard-logs/ 
2. https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/event_processing/event_accumulator.py#L210

So I removed tensorflow dependency. And changed the log parsing code. It works very well on the main branch.

## Checklist before requesting a review
- [ ] This is based on the /dev branch (Or a fork of it)
- [x] This was created or at least validated using a proper IDE
- [x] I have tested this code and validated any modified functions
- [x] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

### CODE REVIEW

**Comment by saunderez** [comment]
I'll test your commit with my branch (dev-vlad)...there's minimal difference between it and dev so if its good for me it should be fine to push.

**Comment by saunderez** [comment]
Everything seems to be good, I've merged with my branch and just about to pushed to is so others can test

**Comment by ArrowM** [comment]
Changing base to dev, we want to test all PRs through that branch before going to main.

**Comment by ArrowM** [comment]
Looks good to me. Merged to dev. Thanks!

**Pull request merged**
