### PR TITLE
very urgent fix for accelerator init

### PR DESCRIPTION
**Pull request by FurkanGozukara**
it was throwing error

fixed

logging_dir = logging_dir

### CODE REVIEW

**Comment by ArrowM** [comment]
you probably have the wrong version of accelerator installed

**Comment by d8ahazard** [comment]
> you probably have the wrong version of accelerator installed

Beat me to it.

**Comment by FurkanGozukara** [comment]
> > you probably have the wrong version of accelerator installed
> 
> Beat me to it.

how to fix it? i am running on runpod. I installed requirements as well

**Comment by FurkanGozukara** [comment]
fixed with this

pip install --upgrade --no-deps --force-reinstall -r requirements.txt

**Pull request closed without merging**
