### PR TITLE
Implement option to save extra_networks lora.py

### PR DESCRIPTION
**Pull request by gammagoat**
## Describe your changes

When option is selected, when saving loras (modelname_steps.pt) we will also save modelname_steps.safetensors that is compatible with a1111 extra networks.

This change implements a new safetensor format for loras.
 - It does not support extended lora
 - We move .pt file generation to a new folder db_loras configured as db_lora_models_path. Introduce ui_lora_models_path for extra networks models.

## Checklist before requesting a review
- [x] This is based on the /dev branch (Or a fork of it)
- [x] This was created or at least validated using a proper IDE
- [x] I have tested this code and validated any modified functions
- [x] I have added the appropriate documentation and hint strings if adding or changing a user-facing feature

### CODE REVIEW

**Comment by JackEllie** [comment]
Looking forward to implementing this feature

**Comment by d8ahazard** [comment]
Let's get this baby into dev and test it out!

**Comment by gammagoat** [comment]
Yeah, let me get also undo the db_lora path stuff. I have another pr coming to move the Loras into the model dir.

**Comment by gammagoat** [comment]
Oops.

**Pull request merged**
