### PR TITLE
Feature: increase max token length

### PR DESCRIPTION
**Pull request by sgsdxzy**
Allow maximum of 300 token length (in fact we can support infinite, but 300 is already enough).
Based on #85 so please merge that first.
Needs some thorough test, I have to touch a lot of stuff to make max token length work. The default of 75 should at least be safe though.

### CODE REVIEW

**Comment by d8ahazard** [comment]
Do me a favor - set the default max token length to something longer than 75. ;)

**Comment by sgsdxzy** [comment]
> Do me a favor - set the default max token length to something longer than 75. ;)

I think 75 is fine for most use cases. If one does not use [filewords], one cannot exceeds 75. 300 is just for when you have ~k images and use deepdanbooru to auto tag them and hate to truncate.

**Comment by sgsdxzy** [comment]
To keep old behavior exactly the same, token limit cannot be raised when not pad_tokens. Should I put this information somewhere?

**Comment by mykeehu** [comment]
@sgsdxzy  For example, I didn't know what the Pad Tokens were for, so I didn't turn them on in my models. The description didn't tell me much.

**Comment by d8ahazard** [comment]
> To keep old behavior exactly the same, token limit cannot be raised when not pad_tokens. Should I put this information somewhere?

Looks good. Please update readme.md with your added/changed features, and a bit of info on what they do and how to use them.

Thanks again for the contributions. ;)

**Pull request merged**
